# Generated by Django 4.1 on 2022-08-04 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_username_profile_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile", old_name="name", new_name="username",
        ),
    ]
