# Generated by Django 4.0.6 on 2022-08-07 02:23

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_name_profile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='post_images')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('no_likes', models.IntegerField(default=0)),
            ],
        ),
    ]
