# Generated by Django 4.0.6 on 2022-08-07 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
