# Generated by Django 4.0.6 on 2022-08-09 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
